language: java
before_install:
- openssl aes-256-cbc -K $encrypted_6a082e96d08b_key -iv $encrypted_6a082e96d08b_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/ENV_DEPLOY_KEY
- mkdir ~/ofbiz
- cd ~/ofbiz
- git clone https://github.com/blockfreight/ofbiz-erp.git .
install:
- docker-compose up -d
after_success:
  - bash ./deploy.sh