language: java
sudo: required
services:
- docker
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export REPO=blockfreight/ofbiz-erp
- export TAG=ci-cd
- docker build -f ofbiz/Dockerfile -t $REPO .
- docker tag $REPO $REPO:$TAG
- docker push $REPO:$TAG
after_success:
- openssl aes-256-cbc -K $encrypted_6a082e96d08b_key -iv $encrypted_6a082e96d08b_iv -in travis_rsa.enc -out travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add /tmp/deploy_rsa
- mv travis_rsa ~/.ssh/ENV_DEPLOY_KEY
deploy:
    provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: ci-cd