language: java
sudo: required
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export REPO=blockfreight/ofbiz-erp
- export TAG=ci-cd
# - docker build -f ofbiz/Dockerfile -t $REPO .
- docker build -f ofbiz/Dockerfile -t $REPO --build-arg OFBIZ_DB=$ENV_OFBIZ_DB --build-arg OFBIZ_OLAP_DB=$ENV_$OFBIZ_OLAP_DB --build-arg OFBIZ_TENANT_DB=$ENV_OFBIZ_TENANT_DB --build-arg POSTGRES_USER=$ENV_POSTGRES_USER --build-arg POSTGRES_PASSWORD=$ENV_POSTGRES_PASSWORD .
- docker tag $REPO $REPO:$TAG
- docker push $REPO:$TAG
before_deploy:
- openssl aes-256-cbc -K $encrypted_6a082e96d08b_key -iv $encrypted_6a082e96d08b_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add /tmp/deploy_rsa
# - mv travis_rsa ~/.ssh/ENV_DEPLOY_KEY
deploy:
    provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: ci-cd